### ISSUE TITLE
Peer to Peer Code Review

### ISSUE THREAD

**Issue by benjp009** [Ewoskyx/leaderboard#6]
# 👋 @Ewoskyx 

### Great job so far !! 

1. Try to make the responsive items to go one on top of each other 
  - First row : Add your score div 
  - Second row : Recent Score 

2. try to work more on the design, for example:
  - align items 
  - add some white space

**Comment by Ewoskyx** [comment]
Hey @benjp009,
Thank you for the review and suggestions. I totally agree with you and I will work on this as soon as possible. :)
Cheers,

**Comment by edwardoluyara** [comment]
Hello @Ewoskyx,
I think your project looks great there is nothing else to say order than its time to merge it ✔️ ( although it has been merged )
